---
title: "Supplements"
author: "randy"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

citation()
citation("gamlss")
citation("nlme")
citation("JMbayes")

print(citation("nlme"), bibtex=TRUE)
print(citation("gamlss"), bibtex=TRUE)
print(citation("brokenstick"), bibtex=TRUE)
print(citation("JMbayes"), bibtex=TRUE)

library(dplyr)
library(gamlss)
library(JMbayes)
library(brokenstick)
library(report)
report::report_system()
report::report_packages()
report::cite_packages()
```

$$
G = \begin{pmatrix}
7.87 & -4.97 & -4.80 & - 6.72 & -8.05 & -8.11 \\
-4.97 & 12.39 & 2.60 & 7.63 & 3.67 & 5.80 \\
-4.80 & 2.60 & 12.77 & 3.08 & 8.96 & 1.63 \\
-6.72 & 7.63 & 3.08 &  18.56 & -1.38 & 10.90 \\
-8.05 & 3.68 & 8.96 & -1.38 & 46.48 & -23.59 \\
-8.11 & 5.80 & 1.63 & 10.90 & -23.59 & 77.20 \\
\end{pmatrix}
$$

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
