# Preface {.unnumbered}

# Title

1.  Extending People-like-Me Predictions with Mahalanobis distance for Personalized Healthcare: An application to a Longitudinal Study of Growth in Children

2.  Using multiple time matching based Mahalanobis distance People-Like-Me for Longitudinal Studies: A Case and Simulation Study for Child Growth Data

3.  Improving and Comparing People-Like-Me methods for Longitudinal Children Growth Data by Using Mahalanobis and Euclidean Distance

\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\--

# Author and Affliation

-   Elizabeth Juarez-Colunga: elizabeth.juarez-colunga\@cuanschutz.edu

-   Kathryn L. Colborn: kathryn.colborn\@cuanschutz.edu

-   Stef van Buuren: s.vanbuuren\@uu.nl

-   Jennifer E Stevens-Lapsley: JENNIFER.STEVENS-LAPSLEY\@CUANSCHUTZ.EDU

-   Andrew J Kittelson: Andy.Kittelson\@umontana.edu; Andy.Kittelson\@umontana.edu.

-   Chong Kim: chonggg511\@gmail.com

-   Xin Jin: xin.2.jin\@cuanschutz.edu

-   Jeremy Graber: jeremy.graber\@cuanschutz.edu

1.  Department of Biostatistics and Informatics, Colorado School of Public Health, University of Colorado, Aurora, CO, USA.

2.  Netherlands Organization for Applied Scientific Research TNO, Leiden, The Netherlands.

3.  Department of Methodology and Statistics, University of Utrecht, Utrecht, The Netherlands.

4.  Physical Therapy Program, Department of Physical Medicine and Rehabilitation, University of Colorado, Aurora, CO, USA.

5.  Eastern Colorado VA Geriatric Research, Education, and Clinical Center (GRECC), VA Eastern Colorado Health Care System, Aurora, CO, USA.

6.  School of Physical Therapy and Rehabilitation Science, University of Montana, Missoula, MT, USA.

\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\--

## Original Abstract

The use of personalized prediction models has become increasingly popular in healthcare as a support tool for decision-making. These models have been used to inform patients about the potential trajectory of their condition, to estimate prognosis, and to select and evaluate treatments. People-like-me (PLM) is a semi-parametric model based on multiple imputation and predictive mean matching, which produces personalized predictions for an individual patient using data from similar historical patients (neighbors).

This paper introduces an extension to the single-time predictive mean matching PLM approach, using Mahalanobis and Euclidean distance to find the neighbors used for prediction. We applied the extended method to a longitudinal study of growth in children to predict future height.

The effectiveness of the extended method was evaluated in comparison to the single-time PLM approach and prediction based on a linear mixed model. The performance was evaluated in terms of accuracy, precision, and coverage. The results showed that PLM with Mahalanobis distance on multiple-time matching provided a better prediction compared to the single-time-matching and Euclidean distance. The Mahalanobis distance-based PLM provided more accurate estimates and higher coverage.

This paper highlights various conceptual and practical issues for using PLM in real clinical data analysis. The results of this paper suggest that PLM with Mahalanobis distance on multiple-time matching is an effective method for personalized prediction in healthcare, providing more accurate predictions and higher coverage. Future research should focus on further evaluation of the PLM model with other types of healthcare data.

```         
Keywords: Mahalanobis distance; Predictive mean matching; Personalized data-driven prediction; "People-Like-Me"
```

\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\--

## WNAR Abstract

### Objective:

People-like-me is a method based on multiple imputation and predictive mean, to achieve a personalized predictive accuracy. This study is aim to extend the single time predictive mean matching PLM into multiple time and different metrics for matching.

### Materials and Methods:

Longitudinal growth data are valuable to predict the future growth of children. This study include both the analytic application with EPIC dataset as well as a simulation study, to compare different PLM methods and LMM dynamic prediction methods. All of the methods are tested with baseline height and subjects' features to predict the future growth trajectory. Accuracy, precision, and coverage are used to judge the performance of the PLM and LMM methods.

### Results:

In total, 1325 individuals are used for data analysis and simulation study: 913 individuals for training and 442 individuals for testing group. The predictive results from PLMs and LMM are consistent and coherent with observed testing data. The predictive results show that PLM with Mahalanobis distance on multiple-time matching outperformed the method with single-time-matching and Euclidean distance. PLM based on Mahalanobis distance provided more accuracy estimates and higher coverage.

### Discussion:

Over all, the PLM methods can provide accurate and precise prediction on children growth. Mahalanobis distance is a reasonable and robust strategy for the set and size of information donor cohort. With specified assessment for the target subject, PLM can provide a more efficient model. PLM methods and potential extensions can be useful for future personalized clinical analysis. This paper highlighted various conceptual and practical issues for using PLM in real clinical data analysis.

\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\--

## The Final Abstract

In this paper, the authors provides an improved People-like-me (PLM) method based on multiple imputation and predictive mean matching. The proposed method can be used to produce personalized predictions for a given patient using data of similar historical patients. The authors applied the extended method to a longitudinal study of growth in children predicting future height with EPIC dataset. The predictive results show that PLM with Mahalanobis distance on multiple-time matching outperformed the method with single-time-matching and Euclidean distance. Extensive simulation studies were conducted to compare the proposed method to both the single time PLM approach and prediction based on a linear mixed model. The results of this study demonstrate that PLM with Mahalanobis distance on multiple-time point similarity matching can provide more accurate estimates, higher precision, and better coverage for individualized predictions than other models. The paper also discusses the parameter tuning with Mahalanobis-PLM and provides insight for clinical data analysis.

\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\--

## Acknowledging the OSG Consortium

Papers, presentations, and other publications that feature research that benefited from the Open Science Pool resources, services or expertise should cite the following two articles and one DOI:

-   Pordes, R. et al. (2007). "The Open Science Grid", J. Phys. Conf. Ser. 78, 012057.doi:10.1088/1742-6596/78/1/012057.

-   Sfiligoi, I., Bradley, D. C., Holzman, B., Mhashilkar, P., Padhi, S. and Wurthwein, F. (2009). "The Pilot Way to Grid Resources Using glideinWMS", 2009 WRI World Congress on Computer Science and Information Engineering, Vol. 2, pp. 428--432. doi:10.1109/CSIE.2009.950.

-   OSG. (2006). OSPool. OSG. https://doi.org/10.21231/906P-4D78

and include in the text the following acknowledgement:

This research was done using services provided by the OSG Consortium \[1,2\], which is supported by the National Science Foundation awards #2030508 and #1836650.

For your convenience, a BibTex file containing the above two references has been provided.
