---
title: "11_inla_smoothing"
author: "randy"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




```{r}
library(INLA)
library(brinla)
library(splines)
```


```{r}
library("SemiPar")
data(lidar)

xx <- seq(390, 720, by = 5)
# Add data for prediction
new.data <- cbind(range = xx, logratio = NA)
new.data <- rbind(lidar, new.data)

View(new.data)
```


```{r}
knots <- seq(400, 700, by = 10)
m.bs3 <- inla(logratio ~ 1 + bs(range, knots = knots),
  data = new.data, control.predictor = list(compute = TRUE))

summary(m.bs3)
```


```{r}
m.ns3 <- inla(logratio ~ 1 + ns(range, df = 10),
  data = new.data, control.predictor = list(compute = TRUE))
summary(m.ns3)

attr(ns(lidar$range, df = 10), "knots")

```



```{r}
library("INLA")

m.rw1 <- inla(logratio ~ -1 + f(range, model = "rw1", constr = FALSE),
  data = lidar, control.predictor = list(compute = TRUE))
summary(m.rw1)

m.rw2 <- inla(logratio ~ -1 + f(range, model = "rw2", constr = FALSE),
  data = lidar, control.predictor = list(compute = TRUE))
summary(m.rw2)


m.rw1$summary.fitted.values
```


```{r}
ggplot(data = lidar, aes(x = range, y = logratio)) +
  geom_point() +
  geom_line(y = m.rw1$summary.fitted.values$mode, color = "red") +
  geom_line(y = m.rw2$summary.fitted.values$mode, color = "blue")
```


```{r}
lidar$range.grp <- inla.group(lidar$range, n = 50, method = "quantile")
lidar <- lidar %>%
  mutate(id = rep(1:13, 17))
summary(lidar$range.grp)

View(lidar)
```



```{r}
m.grp.rw1 <- inla(logratio ~ -1 + f(range.grp, model = "rw1", constr = FALSE) + 
                    f(id, model = "iid"),
  data = lidar, control.predictor = list(compute = TRUE))
summary(m.grp.rw1)

m.grp.rw2 <- inla(logratio ~ -1 + f(range.grp, model = "rw2", constr = FALSE) +
                    f(id, model = "iid"),
  data = lidar, control.predictor = list(compute = TRUE))
summary(m.grp.rw2)
```



```{r}
ggplot(data = lidar, aes(x = range.grp, y = logratio, group = id)) +
  geom_point() +
  geom_line(aes(y = m.grp.rw1$summary.fitted.values$mode, group = id, color = as.factor(id))) +
  geom_line(aes(y = m.grp.rw2$summary.fitted.values$mode, group = id)) 
```


```{r}
mesh1d <- inla.mesh.1d(seq(390, 720, by = 20)) 
A1 <- inla.spde.make.A(mesh1d, lidar$range)

spde1 <- inla.spde2.matern(mesh1d, constr = FALSE)
spde1.idx <- inla.spde.make.index("x", n.spde = spde1$n.spde)

View(spde1)
View(spde1.idx)
```


```{r}
stack <- inla.stack(data = list(y = lidar$logratio),
                    A = list(1, A1),
                    effects = list(Intercept = rep(1, nrow(lidar)), spde1.idx),
                    tag = "est")

# Predict at a finer grid
xx <- seq(390, 720, by = 5)
A.xx <- inla.spde.make.A(mesh1d, xx)
stack.pred <- inla.stack(data = list(y = NA),
                         A = list(1, A.xx),
                         effects = list(Intercept = rep(1, length(xx)), spde1.idx),
                         tag = "pred")


joint.stack <- inla.stack(stack, stack.pred)
formula <- y ~ -1 + f(x, model = spde1)
m.spde <- inla(formula, data = inla.stack.data(joint.stack),
               control.predictor = list(A = inla.stack.A(joint.stack), compute = TRUE))


ggplot(data = lidar, aes(x = range, y = logratio)) +
  geom_point() +
  geom_line(aes(y = m.spde$summary.fitted.values$mode[1:221]))

length(m.spde$summary.fitted.values$mean)
```


















