---
title: "02_marginal_simulation"
author: "Randy"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup}
knitr::opts_chunk$set(collapse = TRUE,
                      comment = "#>")

library(tidyverse)
library(splines)
library(nlme)
devtools::load_all()
```

```{r "model", cache=TRUE}
ctrl <- lmeControl(opt = 'optim')


# fit1 <-  lme(ht ~ bs(time, degree = 3) * sex - 1,
#               random = ~ 1 + time| id,
#               control = ctrl,
#               data = all)
# 
# fit2 <-  lme(ht ~ bs(time, knots = c(10, 12, 15), degree = 3) * sex - 1,
#               random = ~ 1 + time| id,
#               control = ctrl,
#               data = all)

## df 3 = intercept 0 + knots 3
# fit3 <-  lme(ht ~ bs(time, knots = c(10, 12, 15), degree = 3) * sex - 1,
#               random = ~ 1 + bs(time, df = 3, intercept = FALSE)| id,
#               control = ctrl,
#               data = all)
# 
# ## df 4 = linear 0 + knots 3
# fit4 <-  lme(ht ~ bs(time, knots = c(10, 12, 15), degree = 3) * sex - 1,
#               random = ~ 1 + bs(time, df = 4, degree = 1, intercept = FALSE)| id,
#               control = ctrl,
#               data = all)

## df 5 = quadratic 2 + knots 3
fit5 <-  lme(ht ~ bs(time, knots = c(10, 12, 15), degree = 3) * sex - 1,
              random = ~ 1 + bs(time, df = 5, degree = 2, intercept = FALSE)| id,
              control = ctrl,
              data = all)

```


```{r "glance"}
## AIC = 190908.2 bs(time, degree = 3)
# glance1 <- broom.mixed::glance(fit1) %>% 
#   mutate(fixed = "fixed = bs(time, degree = 3)", 
#          random = "random = ~ time| id")
# 
# ## AIC = 182505.4	bs(time, degree = 3) knots c(10, 12, 15)
# glance2 <- broom.mixed::glance(fit2) %>%
#     mutate(fixed = "fixed = bs(time, degree = 3, knots = c(10, 12, 15))", 
#          random = "random = ~ time| id")
# 
# ## AIC = 155805.1	intercept df3
# glance3 <- broom.mixed::glance(fit3) %>%
#       mutate(fixed = "fixed = bs(time, degree = 3, knots = c(10, 12, 15))", 
#          random = "random = ~ bs(time, df = 3, degree = 0)")
# 
# ## AIC = 151773.3 linear df4 
# glance4 <- broom.mixed::glance(fit4) %>%
#       mutate(fixed = "fixed = bs(time, degree = 3, knots = c(10, 12, 15))", 
#          random = "random = ~ bs(time, df = 4, degree = 1)")

## AIC = 145323.4 quadratic df5
glance5 <- broom.mixed::glance(fit5) %>%
      mutate(fixed = "fixed = bs(time, degree = 3, knots = c(10, 12, 15))", 
         random = "random = ~ bs(time, df = 5, degree = 2)")


# result <- rbind(glance1, glance2, 
#                 glance3, glance4, glance5) %>%
#   as.data.frame() %>% 
#   dplyr::select(-nobs) %>%
#   dplyr::select(fixed, random, everything()) %>%
#   arrange(AIC) 
# 
# result
```

```{r "tidy", eval=FALSE, include=FALSE}
# (tidy3 <- broom.mixed::tidy(fit3))
# (vcov3 <- getVarCov(fit3))
# (tidy4 <- broom.mixed::tidy(fit4))
# (vcov4 <- getVarCov(fit4))
(tidy5 <- broom.mixed::tidy(fit5))

```

```{r "augment"}
augment5 <- broom.mixed::augment(fit5)

margin_mean <- augment5 %>%
  dplyr::select(id, sex, time, `.fixed`)

margin_mean

fit5$sigma
```

```{r "random vcov"}
(vcov5 <- getVarCov(fit5))
```

```{r message=FALSE, warning=FALSE}
# library(furrr)
# # Set a "plan" for how the code should run.
# plan(multisession, workers = 6)
# library(tictoc)

tic()
# This does run in parallel!
simulation_1k <- map(1:1000, 
                     ~gen_all_ranef(seed = .x))
toc()

```



```{r}
library(furrr)
# Set a "plan" for how the code should run.
plan(multisession, workers = 6)
library(tictoc)

tic()
estimation_1k <- map(simulation_1k, 
                     ~lme(ht ~ bs(time, knots = c(10, 12, 15), degree = 3) * sex - 1,
                          random = ~ 1 + bs(time, df = 5, degree = 2, intercept = FALSE)| id,
                          control = ctrl,
                          data = .x))
toc()
```

