


```{r}
library(tidyverse)
library(doParallel)
library(foreach)
library(tictoc)

# devtools::install_github("Goodgolden/plmlmm", foce = TRUE)

library(plmlmm)
# devtools::load_all()
# simulation_20 <- simulation_20[1:20]
# save(simulation_20, file = "plmlmm_simulation_20_dataset_20220824.Rdata")
load("Z:/plmlmm/package/plmlmm_simulation_20_dataset_20220824.Rdata")
```


```{r}

detectCores()
myCluster <- makeCluster(20, # number of cores to use
                         type = "PSOCK") # type of cluster

registerDoParallel(myCluster)

timea <- Sys.time()

output_eld <- foreach(i = 1:20,
                  .export = ls(globalenv()),
                  .packages = "plmlmm") %dopar% {

    .GlobalEnv$simulation_20 <- simulation_20
    `%!in%` <- Negate(`%in%`)
    train_data <- dplyr::filter(simulation_20[[i]], group == "training")
    id_train <- unique(train_data$id)
    bks_pred <-
     plmlmm::brokenstick_prediction(
        outcome = "ht",
        time = "time",
        id = "id",
        train_data = train_data,
        knots = c(5, 10, 12),
        pred_time = c(2, 4, 6, 8, 10, 12),
        # newdata = test_baseline,
        choice = "predicted")
    lb_data <-
      plmlmm::linear_brokenstick(
        lm_formula = "`.pred` ~ time * sex + baseline",
        bks_pred = bks_pred)
    eld_n10 <- map(id_train,
                   ~plmlmm::pred_matching(
                     lb_data = lb_data,
                     obs_data = train_data,
                     match_methods = "euclidean",
                     match_num = 10,
                     gamlss_formula = "ht ~ cs(time, df = 3)",
                     gamsigma_formula = "~ cs(time, df = 1)",
                     match_plot = FALSE,
                     predict_plot = FALSE,
                     sbj = .))
   eld_n10
                  }
save(output_eld, file = "plmlmm_simulation_output_eld_dataset1_results_20220824.Rdata")
remove(output_eld)
stopCluster(myCluster)
timeb <- Sys.time()
timeb - timea

```


```{r}
myCluster <- makeCluster(20, # number of cores to use
                         type = "PSOCK") # type of cluster
registerDoParallel(myCluster)
timea <- Sys.time()
output_mhlp <- try( foreach(i = 1:20, 
                  .export = ls(globalenv()), 
                  .packages = "plmlmm") %dopar% {
    .GlobalEnv$simulation_20 <- simulation_20
    `%!in%` <- Negate(`%in%`)
    train_data <- dplyr::filter(simulation_20[[i]], group == "training")
    id_train <- unique(train_data$id)
    bks_pred <- 
     plmlmm::brokenstick_prediction(
        outcome = "ht",
        time = "time",
        id = "id",
        train_data = train_data,
        knots = c(5, 10, 12),
        pred_time = c(2, 4, 6, 8, 10, 12),
        # newdata = test_baseline,
        choice = "predicted")
    lb_data <- 
      plmlmm::linear_brokenstick(
        lm_formula = "`.pred` ~ time * sex + baseline",
        bks_pred = bks_pred)
    mhl_p09 <- map(id_train,
                   ~try(plmlmm::pred_matching(
                     lb_data = lb_data,
                     obs_data = train_data,
                     match_methods = "mahalanobis",
                     match_alpha = 0.9,
                     gamlss_formula = "ht ~ cs(time, df = 3)",
                     gamsigma_formula = "~ cs(time, df = 1)",
                     match_plot = FALSE,
                     predict_plot = FALSE,
                     sbj = .)))
   mhl_p09})

save(output_mhlp,
     file = "plmlmm_simulation_output_mhlp_dataset1_results_20220824.Rdata")
remove(output_mhlp)
stopCluster(myCluster)
timeb <- Sys.time()
timeb - timea
```



```{r}
detectCores()
myCluster <- makeCluster(20, # number of cores to use
                         type = "PSOCK") # type of cluster

registerDoParallel(myCluster)

timea <- Sys.time()
output_mhln <- foreach(i = 1:20, 
                  .export = ls(globalenv()), 
                  .packages = "plmlmm") %dopar% {
  
    .GlobalEnv$simulation_20 <- simulation_20
    `%!in%` <- Negate(`%in%`)
    train_data <- dplyr::filter(simulation_20[[i]], group == "training")
    id_train <- unique(train_data$id)
    bks_pred <- 
     plmlmm::brokenstick_prediction(
        outcome = "ht",
        time = "time",
        id = "id",
        train_data = train_data,
        knots = c(5, 10, 12),
        pred_time = c(2, 4, 6, 8, 10, 12),
        # newdata = test_baseline,
        choice = "predicted")
    
    lb_data <- 
      plmlmm::linear_brokenstick(
        lm_formula = "`.pred` ~ time * sex + baseline",
        bks_pred = bks_pred)
    
    mhl_n10 <- map(id_train,
                   ~plmlmm::pred_matching(
                     lb_data = lb_data,
                     obs_data = train_data,
                     match_methods = "mahalanobis",
                     match_num = 10,
                     gamlss_formula = "ht ~ cs(time, df = 3)",
                     gamsigma_formula = "~ cs(time, df = 1)",
                     match_plot = FALSE,
                     predict_plot = FALSE,
                     sbj = .))

   mhl_n10}

save(output_mhln, file = "plmlmm_simulation_output_mhln_dataset1_results_20220824.Rdata")
remove(output_mhln)
stopCluster(myCluster)
timeb <- Sys.time()
timeb - timea
```


```{r}
detectCores()
myCluster <- makeCluster(20, # number of cores to use
                         type = "PSOCK") # type of cluster
registerDoParallel(myCluster)
timea <- Sys.time()
output_sgl10_n10 <- foreach(i = 1:20, 
                  .export = ls(globalenv()), 
                  .packages = "plmlmm") %dopar% {
    .GlobalEnv$simulation_20 <- simulation_20
    `%!in%` <- Negate(`%in%`)
    train_data <- dplyr::filter(simulation_20[[i]], group == "training")
    id_train <- unique(train_data$id)
    bks_pred <- 
     plmlmm::brokenstick_prediction(
        outcome = "ht",
        time = "time",
        id = "id",
        train_data = train_data,
        knots = c(5, 10, 12),
        pred_time = c(2, 4, 6, 8, 10, 12),
        # newdata = test_baseline,
        choice = "predicted")
    lb_data <- 
      plmlmm::linear_brokenstick(
        lm_formula = "`.pred` ~ time * sex + baseline",
        bks_pred = bks_pred)

    sgl10_n10 <- map(id_train,
                     ~plmlmm::pred_matching(
                       lb_data = lb_data,
                       obs_data = train_data,
                       match_methods = "single",
                       match_num = 10,
                       match_time = 10,
                       match_alpha = NULL,
                       gamlss_formula = "ht ~ cs(time, df = 3)",
                       gamsigma_formula = "~ cs(time, df = 1)",
                       match_plot = FALSE,      
                       predict_plot = FALSE,
                       sbj = .))
   sgl10_n10}

save(output_sgl10_n10, file = "plmlmm_simulation_output_sgl_dataset1_results_20220824.Rdata")
remove(output_sgl10_n10)
stopCluster(myCluster)
timeb <- Sys.time()
timeb - timea
```




```{r}
# detectCores()
# myCluster <- makeCluster(20, # number of cores to use
#                          type = "PSOCK") # type of cluster
# 
# registerDoParallel(myCluster)

timea <- Sys.time()

output_lmm <- for(i in 1:20) {
  ctrl <- lmeControl(opt = 'optim') 
  train_data <- dplyr::filter(simulation_20[[i]], group == "training")
  fitting <-  lme(ht ~ bs(time, knots = c(10, 12, 15), degree = 3) * sex - 1,
              random = ~ 1 + bs(time, df = 5, degree = 2, intercept = FALSE)| id,
              control = ctrl,
              data = train_data)      
                                    
  lmmpred_95 <- JMbayes::IndvPred_lme(
    lmeObject = fitting,
    newdata = train_baseline,
    timeVar = "time",
    M = 500,
    # times = time_vec,
    all_times = TRUE,
    return_data = TRUE,
    level = 0.95,
    interval = "prediction",
    seed = 555)
  lmmpred_09 <- JMbayes::IndvPred_lme(
    lmeObject = fitting,
    newdata = train_baseline,
    timeVar = "time",
    M = 500,
    # times = time_vec,
    all_times = TRUE,
    return_data = TRUE,
    level = 0.9,
    interval = "prediction",
    seed = 555)
  lmmpred_05 <- JMbayes::IndvPred_lme(
    lmeObject = fitting,
    newdata = train_baseline,
    timeVar = "time",
    M = 500,
    # times = time_vec,
    all_times = TRUE,
    return_data = TRUE,
    level = 0.5,
    interval = "prediction",
    seed = 555)

  lmm_results <-
    dplyr::select(lmmpred_05,
                  id, time,
                  # observed = ht,
                  pred,
                  centile25 = low,
                  centile75 = upp) %>%
    full_join(dplyr::select(lmmpred_09,
                            id, time,
                            # observed = ht,
                            pred,
                            centile05 = low,
                            centile95 = upp),
              by = c("id", "time", "pred")) %>%
    full_join(dplyr::select(lmmpred_95,
                            id, time,
                            # observed = ht,
                            pred,
                            centile025 = low,
                            centile975 = upp),
              by = c("id", "time", "pred"))
    na.omit()
                    
     lmm_results               
                  }
save(output_lmm, file = "plmlmm_simulation_lmm_dataset1_results_20220824.Rdata")
stopCluster(myCluster)
timeb <- Sys.time()
timeb - timea
```

