
```{r}
library(tidyverse)
library(doParallel)
library(foreach)
library(tictoc)

# devtools::install_github("Goodgolden/plmlmm", foce = TRUE)

library(plmlmm)
# devtools::load_all()
# simulation_20 <- simulation_20[1:20]
# save(simulation_20, file = "plmlmm_simulation_20_dataset_20220824.Rdata")
load("Z:/plmlmm/package/plmlmm_simulation_20_dataset_20220824.Rdata")
```


```{r}
detectCores()
myCluster <- makeCluster(20, # number of cores to use
                         type = "PSOCK") # type of cluster

registerDoParallel(myCluster)

timea <- Sys.time()

test_eld <- foreach(i = 1:20,
                  .export = ls(globalenv()),
                  .packages = "plmlmm") %dopar% {

    .GlobalEnv$simulation_20 <- simulation_20
    `%!in%` <- Negate(`%in%`)
    
    ## dataset for training and testing
    train_data <- dplyr::filter(simulation_20[[i]], group == "training")
    test_data <- dplyr::filter(simulation_20[[i]], group == "testing")
    test_baseline <- test_data %>% group_by(id) %>% slice(1L)
    # View(test_baseline)
    
    id_train <- unique(train_data$id)
    id_test <- unique(test_data$id)
    
    train_pred <-
     plmlmm::brokenstick_prediction(
        outcome = "ht",
        time = "time",
        id = "id",
        train_data = train_data,
        knots = c(5, 10, 12),
        pred_time = c(2, 4, 6, 8, 10, 12),
        choice = "predicted")
    
    test_pred <-
     plmlmm::brokenstick_prediction(
        outcome = "ht",
        time = "time",
        id = "id",
        train_data = train_data,
        newdata = test_baseline,
        knots = c(5, 10, 12),
        pred_time = c(2, 4, 6, 8, 10, 12),
        choice = "testing")
    
    lb_train <-
      plmlmm::linear_brokenstick(
        lm_formula = "`.pred` ~ timef * sex + baseline",
        bks_pred = train_pred)

    lb_test <- 
      linear_brokenstick(
        lm_formula = "`.pred` ~ timef * sex + baseline",
        bks_pred = test_pred)
    
    eld_n10 <- map(id_test,
                   ~pred_matching(
                     lb_data = lb_train,
                     lb_test = lb_test,
                     test_data = test_data,
                     train_data = train_data,
                     match_methods = "euclidean",
                     match_num = 10,
                     gamlss_formula = "ht ~ cs(time, df = 3)",
                     gamsigma_formula = "~ cs(time, df = 1)",
                     match_plot = TRUE,
                     predict_plot = TRUE,
                     sbj = .))
   eld_n10
                  }
save(test_eld, file = "plmlmm_simulation_test_eld_dataset1_results_20220824.Rdata")
remove(output_eld)
stopCluster(myCluster)
timeb <- Sys.time()
timeb - timea
```

